# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^.*\.(bin|exe|jpg|png|gif|md)$'
      - id: check-yaml
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.0"
    hooks:
      - id: ruff
        args: [--fix]
        files: ^src/
        types: [python]
      - id: ruff-format
        files: ^src/
        types: [python]
  - repo: local
    hooks:
      - id: ai-prepare-commit-msg
        name: generate commit message with AI
        description: Generate commit message using AI system prompt.
        entry: prepare-commit --verbose
        verbose: true
        log_file: /tmp/prepare-commit.log
        language: python
        stages:
          - prepare-commit-msg
