[project]
name = "ai-prepare-commit"
version = "0.0.1"
description = "AI assistant that generates git commit messages"
dependencies = [
    "click",
    "litellm",
    "GitPython",
    "aiohttp",
    "python-dotenv>=1.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ai_prepare_commit_msg"]

[project.scripts]
prepare-commit = "ai_prepare_commit_msg:cli"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
test = [
    "pytest",
]
spell = [
    "pyspelling",
]
fmt = [
    "black",
    "isort",
    "pyink",
    "ruff",
]

[tool.tox]
env_list = ["3.12"]

[tool.isort]
profile = "black"

[tool.tox.env.test]
description = "Run unit tests"
dependency_groups = [
    "test",
]
commands = [
    [
        "pytest",
        "{posargs}"
    ],
]

[tool.pytest.ini_options]
testpaths = [ "src", "tests" ]
addopts = "--doctest-modules"

[tool.tox.env.spell]
description = "Check spelling in the codebase"
dependency_groups = [
    "spell",
]
commands = [
    [
        "pyspelling",
        "-c",
        ".spellcheck.yml",
    ],
]

[tool.tox.env.fmt]
description = "Format the codebase"
dependency_groups = [
    "fmt",
]
commands = [
    [
        "black",
        ".",
    ],
    [
        "isort",
        ".",
    ],
    [
        "pyink",
        ".",
    ],
    [
        "ruff",
        "format",
    ],
]

