# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: "Maintenance: Scheduled Dependency Version Updates"
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:
permissions: read-all
concurrency:
  group: scheduled-version-updates
  cancel-in-progress: true
jobs:
  check-versions:
    name: Update Managed Version Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          persist-credentials: true
      - name: Setup Go environment
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.26.0"
          cache: false
      - name: Create pull request for version updates
        uses: technote-space/create-pr-action@91114507cf92349bec0a9a501c2edf1635427bc5 # v2.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          EXECUTE_COMMANDS: |
            ./ci/update_versions.sh
          COMMIT_MESSAGE: "chore: update versions"
          COMMIT_NAME: "electrocucaracha bot"
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: "Upgrade versions files"
  check-dockerfile:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: update Dockerfile
        # yamllint disable-line rule:line-length
        uses: ludeeus/dockerfile-updater@eaf8ea79220d076eb46c127fa9895e3de3e0a512 # 21.01.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          pr_title: "chore: update Dockerfile"
